# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# split-monitor-workspaces: load early (absolute path — ~ is unreliable here)
plugin = /home/rin/.config/hypr/plugins/libsplit-monitor-workspaces.so

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

# NVIDIA environment variables
#env = NVD_BACKEND,direct
#env = LIBVA_DRIVER_NAME,nvidia
#env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# split-monitor-workspaces config
plugin {
    split-monitor-workspaces {
        count = 10                       # 5 workspaces per monitor
        keep_focused = 0                # keeps current workspace focus after reload
        enable_notifications = 1        # disable popup notifications
        enable_persistent_workspaces = 1 # always create 10 per monitor
        enable_wrapping = 0             # optional: cycle wraps around
    }
}





# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf
