# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu
  kb_layout = de
  kb_variant = mac
  kb_options = compose:caps # ,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitity for mouse/trackpack (default: 0)
 sensitivity = -0.7

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Scroll faster in the terminal
# windowrule = scrolltouchpad 1.5, tag:terminal

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
gesture = 3, horizontal, workspace

device {
  name = logitech-pro-x-wireless-2
  sensitivity = -0.7
}

device {
  name = logitech-usb-receiver
  sensitivity = -0.7
}

device {
  name = elan06d8:00-04f3:3195-touchpad
  sensitivity = 0
}

cursor {
    hide_on_key_press = true
    warp_on_change_workspace = 1
    no_hardware_cursors = true
}
